backend:
  name: github
  repo: dacrands/bergen-gatsby-cms

media_folder: static/img
public_folder: /img

collections:
  - name: project
    label: Project
    folder: src/pages/projects
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "projectTemplate" }
      - { name: title, label: Project }
      - { name: image, label: Image, widget: image }
      - { name: abstract, label: Abstract, widget: text}   
      - { name: meeting, label: Meeting, widget: string }
      - { name: video, label: Video, widget: string, required: false, hint: "This should be a youtube embed code"}
      - name: students
        label: Students
        widget: list
        fields:
          - { name: name, label: Name}   
          - { name: email, label: Email}   
      - name: mentors
        label: Mentors
        widget: list
        fields:
          - { name: name, label: Name}   
          - { name: email, label: Email}   
      - name: blog
        label: Blog
        widget: list
        fields:
          - { name: title, label: Title }
          - { name: image, label: Image, widget: image, required: false }
          - { name: date, label: Date, widget: date }
          - { name: body, label: Body, widget: markdown } 
