backend:
  name: github
  repo: dacrands/bergen-gatsby-cms

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "blogTemplate" }
      - { name: title, label: Blog }
      - { label: Image, name: image, widget: image }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown } 
  - name: project
    label: Project
    folder: src/pages/projects
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "projectTemplate" }
      - { label: Project, name: title}
      - { label: Image, name: image, widget: image }
      - { label: Abstract, name: abstract, widget: string}
      - { label: Body, name: body, widget: markdown } 
      - name: blog
        label: Blog
        widget: list
        fields:
          - { name: title, label: Title }
          - { name: image, label: Image, widget: image }
          - { name: date, label: Date, widget: date }
          - { name: body, label: Body, widget: text } 
